### ISSUE TITLE
Did anybody archive the actual rendering code

### ISSUE THREAD

**Issue by Orio-nn** [thedenbruh/brickgl#1]
Looking to modify it but I can't find it anywhere

**Comment by mr-ikar** [comment]
L

**Comment by thedenbruh** [comment]
This repository is actually the rendering code. It was not touched or modified in any way.

**Comment by Grizler556** [comment]
> This repository is actually the rendering code. It was not touched or modified in any way.

im pretty sure its not... its just a fauxgl mod and not the actual rendering code that renders the hats and etc :/

**Comment by tanmuzu** [comment]
I archived it. Im aeo btw grizler

**Comment by tanmuzu** [comment]
> This repository is actually the rendering code. It was not touched or modified in any way.

Its not. Even looking at it you can tell its not. Its a fauxgl port

**Comment by thedenbruh** [comment]
update, a new [repo w/ renderer itself](https://github.com/thedenbruh/brk-renderer) has been uploaded.

Happy hilling!

**Comment by tanmuzu** [comment]
> update, a new [repo w/ renderer itself](https://github.com/thedenbruh/brk-renderer) has been uploaded.
> 
> Happy hilling!

im working on opensourcing a renderer that has been rewritten to work without lambda.
